---
title: "Practical Machine Learning Course Project"
author: "Madhu Kanya Das"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    toc: true
    toc_depth: 2
---

## Background

With the increasing availability of wearable devices such as Jawbone Up, Nike FuelBand, and Fitbit, it has become possible to collect large amounts of personal activity data at relatively low cost. These devices are part of the quantified self movement, in which individuals record measurements about their daily activities to improve health outcomes or explore behavioral patterns.

While users often quantify how much physical activity they perform, less attention is given to evaluating how well activities are executed. Proper exercise technique is essential for effectiveness and injury prevention.

In this project, accelerometer data from the belt, forearm, arm, and dumbbell of six participants are used. Participants performed barbell lifts both correctly and incorrectly in five different ways. The goal is to predict the manner in which the exercise was performed using sensor data.

---

## Data Loading and Preprocessing

```{r message=FALSE, warning=FALSE}
library(caret)
library(randomForest)
library(ggplot2)

trainUrl <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testUrl  <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"

training <- read.csv(trainUrl, na.strings = c("NA", "", "#DIV/0!"))
testing  <- read.csv(testUrl,  na.strings = c("NA", "", "#DIV/0!"))
